### PR TITLE
Upgrade dependencies to build using scala 2.12

### PR DESCRIPTION
**Pull request by andrewsmartin**
For #596

### CODE REVIEW

**Comment by xuwei-k** [comment]
```
[error] /home/travis/build/non/spire/core/shared/src/main/scala/spire/std/option.scala:12: value combine is not a member of spire.algebra.Semigroup[A]
[error]     case (Some(x), Some(y)) => Some(x |+| y)
[error]                                       ^
[error] /home/travis/build/non/spire/core/shared/src/main/scala/spire/syntax/std/Ops.scala:91: too many arguments for method combine: (as: TraversableOnce[A])A
[error]     cfor(0)(_ < arr.length, _ + 1) { i => result |+|= arr(i) }
[error]                                                  ^
[error] two errors found
[error] (coreJVM/compile:compileIncremental) Compilation failed
```

https://travis-ci.org/non/spire/jobs/174922463#L804

we should merge first https://github.com/non/spire/pull/600 or something

**Comment by andrewsmartin** [comment]
@xuwei-k Will that be merged any time soon?

**Comment by denisrosset** [comment]
The tests are failing because the latest machinist aligned its method names on `cats-kernel`, and the current Spire release is lagging in that respect. I propose to upgrade machinist and patch manually to revert the method names to the prior convention.

**Comment by denisrosset** [comment]
Should we drop 2.10?

**Comment by denisrosset** [comment]
I introduced a minimal set of changes in #606, keeping a build for Scala 2.10.6.

Thanks @andrewsmartin for the preliminary work!
